services:
  postgres:
    image: postgres:15
    container_name: postgres-container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: userpassword
      POSTGRES_DB: currency_exchange_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: currency-exchange-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/currency_exchange_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: userpassword
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres-data: